package dev.lucasnlm.antimine.gdx

object AtlasNames {
    const val CORE = "core"
    const val BOTTOM = "b"
    const val TOP = "t"
    const val RIGHT = "r"
    const val LEFT = "l"
    const val CORNER_TOP_LEFT = "c-t-l"
    const val CORNER_TOP_RIGHT = "c-t-r"
    const val CORNER_BOTTOM_RIGHT = "c-b-r"
    const val CORNER_BOTTOM_LEFT = "c-b-l"
    const val BORDER_CORNER_RIGHT = "bc-t-r"
    const val BORDER_CORNER_LEFT = "bc-t-l"
    const val BORDER_CORNER_BOTTOM_RIGHT = "bc-b-r"
    const val BORDER_CORNER_BOTTOM_LEFT = "bc-b-l"
    const val FILL_TOP_LEFT = "t-l-tl"
    const val FILL_TOP_RIGHT = "t-r-tr"
    const val FILL_BOTTOM_RIGHT = "b-r-br"
    const val FILL_BOTTOM_LEFT = "b-l-bl"
    const val FULL = "full"
    const val SINGLE = "single"
    const val SINGLE_BACKGROUND = "single-background"
    const val NUMBER_1 = "number-1"
    const val NUMBER_2 = "number-2"
    const val NUMBER_3 = "number-3"
    const val NUMBER_4 = "number-4"
    const val NUMBER_5 = "number-5"
    const val NUMBER_6 = "number-6"
    const val NUMBER_7 = "number-7"
    const val NUMBER_8 = "number-8"
    const val FLAG = "flag"
    const val MINE = "mine"
    const val QUESTION = "question"
}
