package dev.lucasnlm.antimine.gdx

object TextureTheme {
    const val standard = "standard.png"
    const val square = "square.png"
    const val square2 = "square-2.png"
}

object AtlasNames {
    const val core = "core"
    const val bottom = "b"
    const val top = "t"
    const val right = "r"
    const val left = "l"
    const val cornerTopLeft = "c-t-l"
    const val cornerTopRight = "c-t-r"
    const val cornerBottomRight = "c-b-r"
    const val cornerBottomLeft = "c-b-l"
    const val borderCornerTopRight = "bc-t-r"
    const val borderCornerTopLeft = "bc-t-l"
    const val borderCornerBottomRight = "bc-b-r"
    const val borderCornerBottomLeft = "bc-b-l"
    const val fillTopLeft = "t-l-tl"
    const val fillTopRight = "t-r-tr"
    const val fillBottomRight = "b-r-br"
    const val fillBottomLeft = "b-l-bl"
    const val full = "full"
    const val single = "single"
    const val singleBackground = "single-background"
    const val number1 = "number-1"
    const val number2 = "number-2"
    const val number3 = "number-3"
    const val number4 = "number-4"
    const val number5 = "number-5"
    const val number6 = "number-6"
    const val number7 = "number-7"
    const val number8 = "number-8"
    const val flag = "flag"
    const val mine = "mine"
    const val question = "question"
}
